from django.urls import path

from . import views

app_name = "evaluations"

urlpatterns = [
    path(
        "create/",
        view=views.EvaluationCreate.as_view(),
        name="create_fresh"
    ),
    path(
        "create/<int:activity_id>/",
        view=views.EvaluationCreate.as_view(),
        name="create"
    ),
    path(
        "edit/<int:evaluation_id>/",
        view=views.EvaluationEdit.as_view(),
        name="edit"
    ),
    path(
        "detail/<int:evaluation_id>/",
        view=views.EvaluationDetail.as_view(),
        name="detail"
    ),
    path(
        "delete/<int:id>/",
        view=views.EvaluationDelete.as_view(),
        name="delete"
    ),
    path(
        "view/<int:evaluation_id>/",
        view=views.EvaluationView.as_view(),
        name="view"
    ),
    path(
        "",
        view=views.EvaluationList.as_view(),
        name="list"
    ),
    path(
        "groups/evaluate/<int:group_evaluation_id>/print/",
        view=views.GroupEvaluationPrint.as_view(),
        name="group_evaluation_print"
    ),
    path(
        "groups/evaluate/<int:group_evaluation_id>/",
        view=views.GroupEvaluate.as_view(),
        name="evaluate"
    ),
    path(
        "groups/evaluate/<int:group_evaluation_id>/finalize/",
        view=views.GroupEvaluateFinalize.as_view(),
        name="finalize"
    ),
    path(
        "groups/<int:group_evaluation_id>/delete/",
        view=views.GroupEvaluationDelete.as_view(),
        name="group_evaluation_delete"
    ),
    path(
        "student/evolution/<int:group_evaluation_id>/<int:student_id>/",
        view=views.StudentEvolution.as_view(),
        name="student_evolution"
    ),
    path(
        "groups/",
        view=views.GroupEvaluationsList.as_view(),
        name="group_evaluations_list"
    ),
    path(
        "anecdotal-records/edit/<int:anecdotal_record_id>/",
        view=views.AnecdotalRecordEdit.as_view(),
        name="anecdotal_record_edit"
    ),
    path(
        "student/<int:student_id>/anecdotal-records/",
        view=views.AnecdotalRecordStudentDetail.as_view(),
        name="anecdotal_record_student_detail"
    ),
    path(
        "anecdotal-records/<int:anecdotal_record_id>/",
        view=views.AnecdotalRecordDetail.as_view(),
        name="anecdotal_record_detail"
    ),
    path(
        "anecdotal-records/create/",
        view=views.AnecdotalRecordCreate.as_view(),
        name="anecdotal_records_create"
    ),
    path(
        "anecdotal-records/",
        view=views.AnecdotalRecordList.as_view(),
        name="anecdotal_records_list"
    ),
    path(
        "groups/download-pdf/",
        view=views.EvaluationViewPDF.as_view(),
        name="evaluation_view_PDF"
    ),
    path(
        "student/<int:student_id>/anecdotal-records/download-pdf/",
        view=views.AnecdotalRecordStudentDetailPDF.as_view(),
        name="anecdotal_record_student_detail_PDF"
    ),
]
